/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company;

import static com.company.Gui_game.music;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JButton;

import java.awt.*;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public void Credit(boolean e){
        j3.setVisible(e);
        j4.setVisible(e);
        j5.setVisible(e);
        j6.setVisible(e);
        j7.setVisible(e);
        j8.setVisible(e);
        jLabel1.setVisible(e);
       jLabel2.setVisible(e);
    }
    public void keypressed(KeyEvent e){
        
    int code=e.getKeyCode();
        if (code==KeyEvent.VK_UP){
            
        }
    }
    public void setcolor(JButton p,int i){
        p.setBackground(new Color(255,i,0));
        
    }
    public void resetcolor(JButton p1){
        p1.setBackground(new Color(240,240,240));
        
    }
    public Gui() {
        
        
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        
        initComponents();
        Toolkit tk =Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
       
       jLabel1.setVisible(false);
       jLabel2.setVisible(false);
       j3.setVisible(false);
        j4.setVisible(false);
             

        Back.setVisible(false);
        j5.setVisible(false);
        j6.setVisible(false);
        j7.setVisible(false);
        j8.setVisible(false);
        
       
        this.setSize(xsize,ysize);
        background.setSize(xsize, ysize);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();
        credit = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        j6 = new javax.swing.JLabel();
        j7 = new javax.swing.JLabel();
        j8 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        start.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        start.setForeground(new java.awt.Color(240, 240, 240));
        start.setText(" Start Game");
        start.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        start.setContentAreaFilled(false);
        start.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        start.setFocusCycleRoot(true);
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                startMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                startMouseReleased(evt);
            }
        });
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        start.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                startKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                startKeyTyped(evt);
            }
        });
        getContentPane().add(start);
        start.setBounds(800, 230, 350, 70);

        credit.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        credit.setForeground(new java.awt.Color(255, 255, 255));
        credit.setText(" Credit");
        credit.setContentAreaFilled(false);
        credit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                creditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                creditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                creditMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                creditMouseReleased(evt);
            }
        });
        credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditActionPerformed(evt);
            }
        });
        getContentPane().add(credit);
        credit.setBounds(800, 320, 350, 80);

        Exit.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("  Exit");
        Exit.setContentAreaFilled(false);
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitMouseReleased(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(800, 430, 350, 60);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel1.setText("This game was done by second year Software Engineering students.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 240, 1290, 40);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel2.setText("Game Creators:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 290, 340, 90);

        j3.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        j3.setText("Hossam Bassem");
        getContentPane().add(j3);
        j3.setBounds(210, 380, 350, 30);

        j4.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        j4.setText("Aladdin Elkashawy");
        getContentPane().add(j4);
        j4.setBounds(210, 420, 420, 40);

        j5.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        j5.setText("Goher Assem");
        getContentPane().add(j5);
        j5.setBounds(210, 470, 290, 30);

        j6.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        j6.setText("Ahmed yasser");
        getContentPane().add(j6);
        j6.setBounds(210, 510, 320, 40);

        j7.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        j7.setText("Mohammad Tarek");
        getContentPane().add(j7);
        j7.setBounds(210, 560, 380, 30);

        j8.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        j8.setText("Karim Tarek");
        getContentPane().add(j8);
        j8.setBounds(210, 600, 340, 30);

        Back.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 48)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Back");
        Back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        Back.setContentAreaFilled(false);
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BackMouseReleased(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(1670, 970, 160, 60);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/company/assets/maxresdefault.jpg"))); // NOI18N
        background.setMinimumSize(new java.awt.Dimension(0, 0));
        getContentPane().add(background);
        background.setBounds(-10, 0, 1320, 790);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 480, 2, 2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        if (!jLabel1.isShowing()){
        Gui_game c= new Gui_game();
        this.setVisible(false);
        c.setVisible(true);
      }
      
    }//GEN-LAST:event_startActionPerformed

    private void startMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseEntered
    start.setContentAreaFilled(true);
        setcolor(start,223);   
        
    }//GEN-LAST:event_startMouseEntered

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
      if (!jLabel1.isShowing()){
                  System.exit(0);

      }
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditActionPerformed
       start.setVisible(false);
       credit.setVisible(false);
        Credit(true);
      
       Exit.setVisible(false);
       
       Back.setVisible(true);
      
      
        

        // TODO add your handling code here:
    }//GEN-LAST:event_creditActionPerformed

    private void startMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseReleased
      start.resize(350, 70);       // TODO add your handling code here:
    }//GEN-LAST:event_startMouseReleased

    private void startMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseExited
      start.setContentAreaFilled(false);
        resetcolor(start);   
        // TODO add your handling code here:
    }//GEN-LAST:event_startMouseExited

    private void creditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditMouseEntered
    credit.setContentAreaFilled(true);
        setcolor(credit,223);
          credit.resize(350, 70);        // TODO add your handling code here:
    }//GEN-LAST:event_creditMouseEntered

    private void creditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditMouseExited
      credit.setContentAreaFilled(false);
        resetcolor(credit);        // TODO add your handling code here:
    }//GEN-LAST:event_creditMouseExited

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
     Exit.setContentAreaFilled(true);
        setcolor(Exit,223);
         Exit.resize(350, 70);// TODO add your handling code here:
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
     Exit.setContentAreaFilled(false);
        resetcolor(Exit);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitMouseExited

    private void startKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_startKeyTyped
    // TODO add your handling code here:
    }//GEN-LAST:event_startKeyTyped
    
    private void startKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_startKeyPressed
          // TODO add your handling code here:
    }//GEN-LAST:event_startKeyPressed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
     if (!start.isShowing()){
         Back.setVisible(false);
      Credit(false);
        start.setVisible(true);
    
     credit.setVisible(true);
      Exit.setVisible(true);
     }
         // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        Back.setContentAreaFilled(true);
        setcolor(Back,223);  
         Back.resize(160, 60);// TODO add your handling code here:
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
    Back.setContentAreaFilled(false);
        resetcolor(Back);          // TODO add your handling code here:
    }//GEN-LAST:event_BackMouseExited

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_startMouseClicked

    private void startMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMousePressed
    start.resize(340, 60);
      setcolor(start,214);
          music("a");// TODO add your handling code here:
    }//GEN-LAST:event_startMousePressed

    private void creditMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditMouseReleased
       credit.resize(350, 70); // TODO add your handling code here:
    }//GEN-LAST:event_creditMouseReleased

    private void ExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseReleased
      Exit.resize(350, 70);  // TODO add your handling code here:
    }//GEN-LAST:event_ExitMouseReleased

    private void creditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditMousePressed
    credit.resize(340, 60);
      setcolor(credit,214); 
       music("a");   // TODO add your handling code here:
    }//GEN-LAST:event_creditMousePressed

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
    Exit.resize(340, 60);
      setcolor(Exit,214); 
       music("a");  // TODO add your handling code here:
    }//GEN-LAST:event_ExitMousePressed

    private void BackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMousePressed
       Back.resize(150, 50);
      setcolor(Back,214);   
       music("a");  // TODO add your handling code here:
    }//GEN-LAST:event_BackMousePressed

    private void BackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseReleased
    Back.resize(160, 60);        // TODO add your handling code here:
    }//GEN-LAST:event_BackMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
                 // music();
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel background;
    private javax.swing.JButton credit;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel j8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
